name: Full Linter CSS + HTML
on: [push]
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2

      - run: yarn install
      - run: npx html-linter --config ./.html-linter.json **/*.html
      - run: npx stylelint --config ./.stylelint.json "**/*.css" --allow-empty-input
      - run: npx eslint --config ./.eslintrc.json "assets/**/*.js" --no-error-on-unmatched-pattern


